Repository salesforce/cloudsplaining, pull requests merged in 2020-06, with the labels that each got.

#55 Leverage PyUp.io
  .pyup.yml
  examples/jira-tickets/Pipfile
  examples/jira-tickets/README.md
  examples/jira-tickets/requirements.txt
Labels: delivery-related

#57 Add CodeQL security scanning
  .github/workflows/codeql.yml
Labels: cla:missing

#58 Add nltk to requirements for ReadTheDocs
  docs/requirements.txt
Labels: documentation

#60 Fixes #59 by moving to Material Mkdocs
  docs/index.md
  docs/requirements.txt
  mkdocs.yml
Labels: documentation
