Repository salesforce/cloudsplaining, pull requests merged in 2020-10, with the labels that each got.

#110 Added Credentials exposure and Service Wildcard to json data file output
  CHANGELOG.md
  cloudsplaining/output/policy_finding.py
  cloudsplaining/scan/group_details.py
  cloudsplaining/scan/inline_policy.py
  cloudsplaining/scan/managed_policy_detail.py
  cloudsplaining/scan/policy_document.py
  cloudsplaining/scan/role_details.py
  cloudsplaining/scan/user_details.py
  cloudsplaining/shared/default-exclusions.yml
  cloudsplaining/shared/utils.py
  requirements.txt
  test/command/test_scan_policy_file.py
  test/files/data_file.json
  test/files/scanning/test_inline_policy_results.json
  test/files/scanning/test_managed_policy_details.json
  test/files/shared/test_exclusions_for_service_roles_expected.json
  test/scanning/test_authorization_details.py
  test/scanning/test_data_file.py
  test/scanning/test_inline_policy.py
  test/scanning/test_managed_policy_detail.py
  test/scanning/test_statement_detail.py
  test/shared/test_exclusions.py
  test/shared/test_utils.py
Labels: enhancement

#113 Cleanup/vue components
  cloudsplaining/output/dist/js/index.js
  cloudsplaining/output/src/components/Principals.vue
  cloudsplaining/output/src/components/finding/AssumeRoleDetails.vue
  cloudsplaining/output/src/components/finding/FindingDetails.vue
  cloudsplaining/output/src/components/finding/PolicyDocumentDetails.vue
  cloudsplaining/output/src/components/principals/PrincipalMetadata.vue
  cloudsplaining/output/src/components/principals/RisksPerPrincipal.vue
  cloudsplaining/output/src/util/principals.js
Labels: ui

#118 Removed extra unit tests - speeds up the unit tests from 3.5 minutes to less than 60 seconds
  CHANGELOG.md
  cloudsplaining/__init__.py
  examples/files/example.json
  examples/files/iam-results-example.json
  tasks.py
  test/command/test_scan_policy_file.py
  test/files/data_file.json
  test/files/example-authz-details.json
  test/files/scanning/test_managed_policy_details.json
  test/scanning/test_authorization_details.py
  test/scanning/test_data_file.py
  test/scanning/test_managed_policy_detail.py
  test/scanning/test_statement_detail.py
  utils/example-iam-data.json
Labels: backend

#124 Adds Credentials Exposure and Service Wildcard to the report
  cloudsplaining/output/dist/js/index.js
  cloudsplaining/output/src/assets/glossary.md
  cloudsplaining/output/src/components/PolicyTable.vue
  cloudsplaining/output/src/components/Principals.vue
  cloudsplaining/output/src/components/Summary.vue
  cloudsplaining/output/src/components/charts/SummaryFindings.vue
  cloudsplaining/output/src/components/finding/RiskAlertIndicators.vue
  cloudsplaining/output/src/components/finding/StandardRiskDetails.vue
  cloudsplaining/output/src/components/principals/RisksPerPrincipal.vue
  cloudsplaining/output/src/util/glossary.js
  cloudsplaining/output/src/util/inline-policies.js
  cloudsplaining/output/src/util/managed-policies.js
  cloudsplaining/output/src/util/other.js
  index.html
Labels: enhancement, ui

#126 Added --minimize option to scan command to reduce report size
  .gitignore
  CHANGELOG.md
  README.md
  cloudsplaining/bin/version.py
  cloudsplaining/command/scan.py
  cloudsplaining/output/report.py
  cloudsplaining/output/template.html
  examples/files/iam-report-example.html
  examples/files/iam-results-example.json
  index.html
  utils/generate_example_report.py
Labels: enhancement, ui

#127 udpate README.md badge link to test action
  README.md
Labels: cla:signed

#128 Implemented Vue router for navbar
  cloudsplaining/output/dist/js/index.js
  cloudsplaining/output/src/App.vue
  cloudsplaining/output/src/main.js
  cloudsplaining/output/src/routes/routes.js
  cloudsplaining/output/src/views/Appendices.vue
  cloudsplaining/output/src/views/AwsPolicies.vue
  cloudsplaining/output/src/views/CustomerPolicies.vue
  cloudsplaining/output/src/views/Guidance.vue
  cloudsplaining/output/src/views/IamPrincipals.vue
  cloudsplaining/output/src/views/InlinePolicies.vue
  cloudsplaining/output/src/views/Summary.vue
  index.html
  package-lock.json
  package.json
Labels: cla:missing, enhancement

#132 Added inline explanations of findings
  cloudsplaining/output/dist/js/index.js
  cloudsplaining/output/src/assets/definition-assumable-by-compute-service.md
  cloudsplaining/output/src/assets/definition-credentials-exposure.md
  cloudsplaining/output/src/assets/definition-data-exfiltration.md
  cloudsplaining/output/src/assets/definition-infrastructure-modification.md
  cloudsplaining/output/src/assets/definition-privilege-escalation.md
  cloudsplaining/output/src/assets/definition-resource-exposure.md
  cloudsplaining/output/src/assets/definition-service-wildcard.md
  cloudsplaining/output/src/assets/how-do-i-validate-results.md
  cloudsplaining/output/src/assets/identifying-false-positives.md
  cloudsplaining/output/src/assets/what-should-i-do.md
  cloudsplaining/output/src/components/finding/AssumeRoleDetails.vue
  cloudsplaining/output/src/components/finding/PrivilegeEscalationDetails.vue
  cloudsplaining/output/src/components/finding/StandardRiskDetails.vue
  index.html
  package-lock.json
Labels: ui

#138 Expand collapse approach changed
  cloudsplaining/output/dist/js/index.js
  cloudsplaining/output/src/components/Button.vue
  cloudsplaining/output/src/components/finding/AssumeRoleDetails.vue
  cloudsplaining/output/src/components/finding/PolicyDocumentDetails.vue
  cloudsplaining/output/src/components/finding/PrivilegeEscalationDetails.vue
  cloudsplaining/output/src/components/finding/StandardRiskDetails.vue
  cloudsplaining/output/src/views/AwsPolicies.vue
  cloudsplaining/output/src/views/CustomerPolicies.vue
  cloudsplaining/output/src/views/InlinePolicies.vue
  index.html
  utils/generate_example_report.py
Labels: cla:signed
