Repository salesforce/cloudsplaining, pull requests merged in 2020-09, with the labels that each got.

#88 Refactored the data file that we are going to use for the data source with Vue
  cloudsplaining/command/scan.py
  cloudsplaining/output/report.py
  cloudsplaining/output/templates/analysis/finding-card/names.html
  cloudsplaining/output/templates/summary/aws-managed.html
  cloudsplaining/output/templates/summary/customer-managed.html
  cloudsplaining/output/triage_worksheet.py
  cloudsplaining/scan/authorization_details.py
  cloudsplaining/scan/group_details.py
  cloudsplaining/scan/inline_policy.py
  cloudsplaining/scan/managed_policy_detail.py
  cloudsplaining/scan/role_details.py
  cloudsplaining/scan/user_details.py
  cloudsplaining/shared/utils.py
  examples/files/example.json
  test/command/test_scan.py
  test/files/new_data_file.json
  test/files/scanning/test_group_detail_results.json
  test/files/scanning/test_inline_policy_results.json
  test/files/scanning/test_role_detail_results.json
  test/files/scanning/test_user_detail_results.json
  test/scanning/test_authorization_details.py
  test/scanning/test_inline_policy.py
  test/scanning/test_new_data_file.py
  test/scanning/test_role_detail_list.py
  test/scanning/test_user_detail_list.py
Labels: backend, enhancement, ui

#92 Fix RTD dependency issue that broke the docs
  docs/requirements.txt
Labels: documentation

#94 Customer vs AWS managed is now clear in the chart. Other small UI fixes. Fixes #93
  CHANGELOG.md
  cloudsplaining/bin/version.py
  cloudsplaining/output/dist/index.bundle.js
  cloudsplaining/output/src/App.vue
  cloudsplaining/output/src/components/ManagedPolicies.vue
  cloudsplaining/output/src/components/Principals.vue
  cloudsplaining/output/src/components/Summary.vue
  cloudsplaining/output/src/components/charts/SummaryFindings.vue
  index.html
Labels: ui

#95 Fix inline policy processing for roles after 2ae75edf
  cloudsplaining/scan/role_details.py
Labels: cla:signed

#100 Added findings for Credentials Exposure and Service Wildcard to scan-policy-file command
  .github/PULL_REQUEST_TEMPLATE
  CHANGELOG.md
  README.md
  cloudsplaining/command/scan_policy_file.py
  cloudsplaining/output/findings.py
  cloudsplaining/output/policy_finding.py
  cloudsplaining/scan/authorization_details.py
  cloudsplaining/scan/principal_detail.py
  cloudsplaining/shared/constants.py
  test/command/test_scan_policy_file.py
  test/output/test_findings.py
  test/output/test_old_findings.py
  test/output/test_policy_finding.py
  test/shared/test_exclusions.py
Labels: enhancement

#102 Disable the task table demo WIP
  cloudsplaining/output/dist/index.bundle.js
  cloudsplaining/output/src/App.vue
  index.html
Labels: ui
