Repository salesforce/cloudsplaining, pull requests merged in 2020-05, with the labels that each got.

#14 Added recursive scanning option - and fixed exclude-actions
  CHANGELOG.md
  README.md
  cloudsplaining/bin/cloudsplaining
  cloudsplaining/command/create_exclusions_file.py
  cloudsplaining/command/expand_policy.py
  cloudsplaining/command/scan.py
  cloudsplaining/command/scan_policy_file.py
  cloudsplaining/output/findings.py
  cloudsplaining/output/templates/guidance/2-triage-guidance.md
  cloudsplaining/output/templates/guidance/4-validation.md
  cloudsplaining/scan/authorization_details.py
  cloudsplaining/shared/exclusions.py
  docs/index.md
  docs/report/triage.md
  docs/report/validation.md
  docs/user-guide/create-exclusions-file.md
  docs/user-guide/overview.md
  docs/user-guide/scan-account.md
  docs/user-guide/scan-policy-file.md
  tasks.py
  test/command/test_scan_policy.py
  test/files/scanning/test_authorization_file_details_missing_constraints_v2.json
  test/output/test_findings.py
  test/scanning/test_authorization_details.py
Labels: bug, enhancement

#18 Migrating to GitHub actions
  .github/workflows/publish.yml
  .github/workflows/test.yml
  .travis.yml
  tasks.py
Labels: delivery-related

#24 Fixes #23 - issue arising from policies with "Deny" with no resource constraints
  CHANGELOG.md
  cloudsplaining/bin/cloudsplaining
  cloudsplaining/scan/policy_document.py
  cloudsplaining/scan/statement_detail.py
  test/scanning/test_policy_document.py
Labels: bug

#25 Fix document onload functionality to select first tab as active
  cloudsplaining/output/templates/template.html
  index.html
Labels: cla:signed

#28 Fix issue #27
  cloudsplaining/scan/statement_detail.py
Labels: cla:missing

#31 Windows compability fix. 0.0.13 bump
  CHANGELOG.md
  README.md
  cloudsplaining/bin/cli.py
  cloudsplaining/output/templates/appendix/references.html
  examples/files/iam-report-example.html
  setup.py
  tasks.py
Labels: bug

#32 Increase pytest coverage for dependabot confidence
  cloudsplaining/command/scan.py
  cloudsplaining/command/scan_policy_file.py
  cloudsplaining/output/data_file.py
  cloudsplaining/output/findings.py
  cloudsplaining/scan/assume_role_policy_document.py
  cloudsplaining/scan/authorization_details.py
  cloudsplaining/scan/policy_detail.py
  cloudsplaining/scan/policy_document.py
  cloudsplaining/scan/principal_detail.py
  cloudsplaining/scan/statement_detail.py
  cloudsplaining/shared/utils.py
  cloudsplaining/shared/validation.py
  examples/files/iam-report-example.html
  setup.cfg
  test/command/test_scan_policy.py
  test/output/test_findings.py
  test/scanning/test_authorization_details.py
  test/scanning/test_policy_document.py
  test/scanning/test_principal_detail.py
  test/scanning/test_statement_detail.py
  test/scanning/test_trust_policies.py
  test/shared/test_validation.py
Labels: cleanup

#35 Fix Data Exposure tallies missing in AWS Managed Table
  CHANGELOG.md
  cloudsplaining/bin/cli.py
  cloudsplaining/output/templates/guidance/4-validation.md
  cloudsplaining/output/templates/summary/aws-managed.html
  index.html
Labels: bug

#38 Fix bug in Principals tab with risk count. Added "Attached to Principals" dropdown card.
  CHANGELOG.md
  cloudsplaining/bin/cli.py
  cloudsplaining/command/scan.py
  cloudsplaining/output/templates/analysis/aws-managed.html
  cloudsplaining/output/templates/analysis/customer-managed.html
  cloudsplaining/output/templates/summary/iam-principals.html
  examples/files/iam-report-example.html
  examples/files/iam-results-example.json
  index.html
Labels: bug, enhancement

#43 UI improvements to the Summary Tables. Much more readable when there are a lot of results.
  .gitignore
  CHANGELOG.md
  cloudsplaining/bin/cli.py
  cloudsplaining/bin/version.py
  cloudsplaining/output/html_report.py
  cloudsplaining/output/templates/summary/aws-managed.html
  cloudsplaining/output/templates/summary/customer-managed.html
  cloudsplaining/output/templates/template.html
  examples/files/iam-report-example.html
  index.html
  setup.py
Labels: enhancement, ui

#44 Table checkbox selection and ability to export as CSV
  README.md
  cloudsplaining/bin/cli.py
  cloudsplaining/bin/version.py
  cloudsplaining/output/templates/summary/aws-managed.html
  cloudsplaining/output/templates/summary/customer-managed.html
  cloudsplaining/output/templates/summary/iam-principals.html
  cloudsplaining/output/templates/template.html
  docs/contributing/versioning.md
  docs/example-report.html
  index.html
Labels: enhancement, ui

#49 Initial fix for Policy to Role Mapping
  cloudsplaining/output/findings.py
  cloudsplaining/output/templates/analysis/aws-managed.html
  cloudsplaining/output/templates/analysis/customer-managed.html
  cloudsplaining/output/templates/analysis/finding-card/names.html
  index.html
  test/command/test_scan_policy.py
  test/files/scanning/test_authorization_file_details_missing_constraints_v2.json
  test/output/test_findings.py
  test/scanning/test_authorization_details.py
Labels: enhancement

#51 Report description improvements to address #47. Version 0.1.4 bump
  CHANGELOG.md
  cloudsplaining/bin/version.py
  cloudsplaining/output/templates/summary/aws-managed.html
  cloudsplaining/output/templates/summary/customer-managed.html
  examples/files/iam-principals-example.json
  examples/files/iam-report-example.html
  examples/files/iam-results-example.json
  examples/files/iam-triage-example.csv
  index.html
Labels: report
