Repository salesforce/cloudsplaining, pull requests merged in 2020-12, with the labels that each got.

#144 Improve Privilege Escalation output format in the UI - fixes #114
  CHANGELOG.md
  cloudsplaining/output/dist/js/index.js
  cloudsplaining/output/src/components/finding/PrivilegeEscalationDetails.vue
  cloudsplaining/output/src/components/finding/PrivilegeEscalationFormat.vue
  cloudsplaining/shared/constants.py
  docs/glossary/privilege-escalation.md
  index.html
  utils/generate_example_report.py
Labels: documentation

#146 fix: User-Group relationships are now shown on IAM Principals page (#122)
  cloudsplaining/output/dist/js/index.js
  cloudsplaining/output/src/components/principals/PrincipalMetadata.vue
  cloudsplaining/output/src/test/groups-test.js
  cloudsplaining/output/src/util/groups.js
  index.html
Labels: bug, cla:signed

#148 Add release drafter GitHub Action
  .github/release-drafter.yml
  .github/workflows/release-drafter.yml
  CHANGELOG.md
  docs/contributing/release-drafter.md
  docs/contributing/versioning.md
  mkdocs.yml
Labels: automation

#151 Add deeplinks to report findings (#133)
  cloudsplaining/output/dist/js/index.js
  cloudsplaining/output/src/App.vue
  cloudsplaining/output/src/components/LinkToFinding.vue
  cloudsplaining/output/src/components/Principals.vue
  cloudsplaining/output/src/components/finding/FindingCard.vue
  cloudsplaining/output/src/routes/routes.js
  cloudsplaining/output/src/util/other.js
  index.html
Labels: cla:signed, ui

#150 Add GitHub workflow to combine Dependabot PRs into a single one
  .github/workflows/combine-prs.yml
Labels: automation

#152 Updating dependencies. Fixed some documentation as well.
  cloudsplaining/bin/version.py
  docs/contributing/contributing.md
  docs/contributing/javascript.md
  docs/requirements.txt
  package-lock.json
  requirements-dev.txt
  requirements.txt
  setup.py
  utils/run_tests.sh
Labels: dependency-updates, documentation
