Repository salesforce/cloudsplaining, pull requests merged in 2021-04, with the labels that each got.

#175 Adds short command flags (fixes #171)
  cloudsplaining/command/create_exclusions_file.py
  cloudsplaining/command/download.py
  cloudsplaining/command/expand_policy.py
  cloudsplaining/command/scan.py
  cloudsplaining/command/scan_multi_account.py
  cloudsplaining/command/scan_policy_file.py
Labels: enhancement

#176 Fix some small documentation issues
  README.md
  mkdocs.yml
Labels: documentation

#177 Avoid Flagging If Deny On Scan Actions Without Constraints
  cloudsplaining/scan/policy_document.py
  test/scanning/test_policy_document.py
  test/scanning/test_statement_detail.py
Labels: cla:signed

#180 Fix PyUp with GitHub actions workaround
  .actrc
  .github/exclude-patterns.txt
  .github/workflows/combine-prs.yml
  .github/workflows/python-dependency-updater.yml
  .github/workflows/security.yml
  cloudsplaining/command/scan_multi_account.py
  cloudsplaining/shared/aws_login.py
Labels: dependency-updates

#179 Add quotes around example account numbers
  cloudsplaining/shared/multi-account-config.yml
Labels: cla:signed

#183 Add update automation
  .actrc
  .github/workflows/update.yml
Labels: automation

#184 Add version bump automation
  .github/workflows/bump-version.yml
  utils/bump-version.sh
Labels: automation

#185 Fixes unicode decode error
  cloudsplaining/bin/version.py
  cloudsplaining/output/report.py
  utils/bump-version.sh
Labels: bug
