Repository salesforce/cloudsplaining, pull requests merged in 2021-05, with the labels that each got.

#191 Add type hints to PolicyDocument and StatementDetail
  cloudsplaining/bin/version.py
  cloudsplaining/scan/inline_policy.py
  cloudsplaining/scan/policy_document.py
  cloudsplaining/scan/statement_detail.py
  cloudsplaining/shared/exclusions.py
  cloudsplaining/shared/utils.py
  test/scanning/test_policy_document.py
  test/scanning/test_statement_detail.py
  test/shared/test_exclusions.py
Labels: cla:signed

#194 exclude non restrictable actions from actions_without_constraints
  cloudsplaining/scan/statement_detail.py
  test/scanning/test_policy_document.py
  test/scanning/test_statement_detail.py
Labels: bug, cla:signed

#198 update Credentials Exposure actions
  docs/glossary/credentials-exposure.md
Labels: cla:missing

#196 change behavior of has_resource_constraints and add new unrestrictabl…
  cloudsplaining/scan/policy_document.py
  cloudsplaining/scan/statement_detail.py
  test/scanning/test_policy_document.py
  test/scanning/test_statement_detail.py
Labels: bug, cla:signed

#203 Add type hints to scan
  cloudsplaining/scan/assume_role_policy_document.py
  cloudsplaining/scan/authorization_details.py
  cloudsplaining/scan/group_details.py
  cloudsplaining/scan/managed_policy_detail.py
  cloudsplaining/scan/role_details.py
  cloudsplaining/scan/user_details.py
  cloudsplaining/shared/exclusions.py
  cloudsplaining/shared/utils.py
  cloudsplaining/shared/validation.py
Labels: cla:signed
