Repository salesforce/cloudsplaining, pull requests merged in 2023-08, with the labels that each got.

#304 Support federated principals
  cloudsplaining/scan/assume_role_policy_document.py
  test/scanning/test_trust_policies.py
Labels: cla:signed

#303 Suppress findings when conditions exist, except when `--flag-all-risky-actions` flag is included
  cloudsplaining/command/scan.py
  cloudsplaining/command/scan_multi_account.py
  cloudsplaining/command/scan_policy_file.py
  cloudsplaining/output/policy_finding.py
  cloudsplaining/scan/inline_policy.py
  cloudsplaining/scan/policy_document.py
  cloudsplaining/scan/statement_detail.py
  test/files/scanning/test_inline_policy_results.json
  test/scanning/test_policy_document.py
Labels: cla:signed

#307 update dependencies and fix mypy and pylint issues
  .pylintrc
  Makefile
  cloudsplaining/command/download.py
  cloudsplaining/command/scan.py
  cloudsplaining/command/scan_multi_account.py
  cloudsplaining/command/scan_policy_file.py
  cloudsplaining/output/policy_finding.py
  cloudsplaining/output/report.py
  cloudsplaining/scan/authorization_details.py
  cloudsplaining/scan/group_details.py
  cloudsplaining/scan/inline_policy.py
  cloudsplaining/scan/managed_policy_detail.py
  cloudsplaining/scan/policy_document.py
  cloudsplaining/scan/role_details.py
  cloudsplaining/scan/user_details.py
  cloudsplaining/shared/aws_login.py
  cloudsplaining/shared/utils.py
  requirements-dev.txt
  requirements.txt
  setup.cfg
Labels: automation, cla:signed, dependency-updates

#310 bump pyyaml to 6.0.1
  requirements.txt
Labels: cla:signed

#309 update GHA workflows and add python version test jobs
  .github/workflows/bump-version.yml
  .github/workflows/nodejs-test.yml
  .github/workflows/publish.yml
  .github/workflows/python-dependency-updater.yml
  .github/workflows/release-drafter.yml
  .github/workflows/security.yml
  .github/workflows/test.yml
  .github/workflows/update-bundle-report.yml
Labels: automation, cla:signed
